<link type='text/css' rel='stylesheet' href='/js/calendar/src/css/jscal2.css' />
<link type='text/css' rel='stylesheet' href='/js/calendar/src/css/border-radius.css' />
<link id='skin-win2k' title='Win 2K' type='text/css' rel='alternate stylesheet' href='/js/calendar/src/css/win2k/win2k.css' />
<script language='javascript' type='text/javascript' src='/js/calendar/src/js/jscal2.js'></script>
<script language='javascript' type='text/javascript' src='/js/calendar/src/js/lang/en.js'></script>



<script type="text/javascript" src="/js/fancybox2/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="/js/fancybox2/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/js/fancybox2/jquery.fancybox-1.3.4.css" media="screen" />



<div id="rightsidemain">
<div id="rightcontentpart">
	<div id="rightsideheading"><img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />Send Email</div>
	<div id="rightsidecontentpart">

	<form method="post" action="<?php echo $this->siteurl?>">
    <table cellspacing="0" cellpadding="0" border="0" class="profile-edit">
        <tbody>
            <tr><td colspan="2"><span class='red'><?php echo $this->msg; ?></span></td></tr>
             <tr>
                <td width="130" id="firstname-label"><label for="patient_name">Patient Name:*</label></td>
                <td class="element"><?php echo $this->form->patient_name;?></td>
            </tr>
            
            <tr>
                <td width="130" id="firstname-label"><label for="date_of_call">Date of Call:*</label></td>
                <td class="element"><?php echo $this->form->date_of_call;?><img src="/images/calendar.png" id="calendar-trigger"></td>
            </tr>

            <tr>
                <td width="130" id="firstname-label"><label for="phone">Phone:*</label></td>
                <td class="element"><?php echo $this->form->phone;?></td>
            </tr>

            <tr>
                <td width="130" id="firstname-label"><label for="phone"></label></td>
                <td class="element"><?php echo $this->form->submit;?>
                    <a id="various1" href="#inline1"  ><input type="button" tabindex="20" class="signup" value="Preview" id="submit" name="preview" ></a>
                    
                </td>
            </tr>
            </table>
            </form>
	</div>

        <div style="display: none;">
		<div id="inline1" style="width:400px;height:500px;overflow:auto;">
			<?php echo stripslashes($this->mail_content);?>
                    
		</div>
	</div>


        
</div>
<div class="btm-curve"><img src="/images/admin-images/btm-r-l.gif" align="left" /><img src="/images/admin-images/btm-r-r.gif" align="right" /></div>
</div>
<script>//<![CDATA[
Calendar.setup(
{ trigger: "calendar-trigger", inputField: "date_of_call",onSelect: function() {
 this.hide();
}
}
);

//]]>
/*$(document).ready(function() {
   
$("#various1").fancybox({
'titlePosition'		: 'inside',
'transitionIn'		: 'none',
'transitionOut'		: 'none'
});
 
});*/
$("#various1").click(function() {

var pname = $('#patient_name').val();
var date =$('#date_of_call').val();
var phone = $('#phone').val();
var doctor_name = '<?php echo addslashes($this->doctor_name); ?>';


$('#dateofcall').html();
$('#dname').html();
$('#pname').html();
$('#pphone').html();
$('#dateofcall').html(date);
$('#pname').html(pname);
$('#pphone').html(phone);
$('#dname').html(doctor_name);

$("#various1").fancybox({
'titlePosition'		: 'inside',
'transitionIn'		: 'none',
'transitionOut'		: 'none'
});

});
</script>
