<div id="rightsidemain">
    <div id="rightcontentpart">
        <div id="rightsideheading">
            <img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />



	Users - <span class='msg'>Total <?php echo $this->total_users ?> user(s) found! </span></div>
        <div id="rightsidecontentpart">
            <?php
            if ($this->total_users > 0) {
            ?>
                <span class='red'>
            <? echo $this->msg; ?>
                </span>
                <br>
<?= $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
            <br>

            <table width='100%' border='0' class='dataTable' cellspacing='0' cellpadding='0'>
                <tr>
                    <th>SNo.</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>User Level</th>

                    <th>Action</th>
                </tr>

<?
                $sno = 0;
                $page = $this->paginator->getCurrentPageNumber();
                $items_per_page = $this->paginator->getItemCountPerPage();
                if ($page > 1) {
                    $sno = $items_per_page * $page - $items_per_page;
                }
                $rowClass = 'trbg1';

                foreach ($this->paginator as $row) {
                    $sno++;

                    if ($rowClass == "trbg1")
                        $rowClass = 'trbg';
                    else
                        $rowClass='trbg1';

                    $userLevel = new Application_Model_UserLevel();
                    $userLevel = $userLevel->find($row['user_level_id']);
?>
                    <tr class='<?= $rowClass ?>'>
                        <td><?= $sno ?></td>
                        <td><?= $row['first_name'] . " " . $row['last_name'] ?></td>
                        <td><?= $row['email'] ?></td>
                        <td><?= $userLevel->getLabel() ?></td>

                        <td>
                            <a href='/admin/user/reset-password/id/<?= $row['id'] ?>'>Reset Password</a>
<?
                    $published = "false.gif";
                    $published_title = "Click here to unblock";
                    if ($row['status'] == 'active') {
                        $published = "true.gif";
                        $published_title = "Click here to block";
                    }

                    $usersNs = new Zend_Session_Namespace("members");
                    $myId = $usersNs->userId;
                    if ($myId == $row['id']) {
 ?>
                        <a href='javascript: void(0)' onclick='alert("You cannot change your block status")'><img src='/images/admin-images/<?php echo $published ?>' border='0' title='<?php echo $published_title ?>'/></a>&nbsp;&nbsp;
                        <?php
                    } else {
                        ?>

                        <a href='/admin/user/block/id/<?= $row['id'] ?>/page/<?= $page ?>'><img src='/images/admin-images/<?php echo $published ?>' border='0' title='<?php echo $published_title ?>'/></a>&nbsp;&nbsp;
                        <?php } ?>

                        <a href='/admin/user/edit/id/<?= $row['id'] ?>/page/<?= $page ?>'><img src='/images/admin-images/edit.gif' border='0' title='Edit'/></a>&nbsp;&nbsp;
                    </td>

                </tr>
<?
                    }
?>
            </table><br />
<?= $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?><br /><br />
<?
                }
?></div>

    </div>
    <div class="btm-curve"><img src="/images/admin-images/btm-r-l.gif" align="left" /><img src="/images/admin-images/btm-r-r.gif" align="right" /></div>
</div>
