<!-- BANNER SECTION -->
<div id="banner-section"><img src="images/home-banner.png" alt="" class="fullimg"></div>
<!--/BANNER SECTION -->
<!-- CONTENT SECTION -->
<div id="content_section" class="clearfix">
  <div class="welcome-section">
    <h2>Welcome to <img src="images/welcome-doctors.png" alt=""></h2>
    <p>doctors is a service that helps patients and doctors communicate in a very rich experience through the doctors online platform. Patients can book appointments online, send secure messages to their doctor, write reviews about doctors and much more!</p>
    <div class="testimonial">
      <p>I recently went to a new doctor and noticed he was located in 
        something called the Professional Building. I felt better right away.<img src="images/quote-close.png" alt=""></p>
      <h4>George Carlin</h4>
    </div>
  </div>
  <div class="ft-content clearfix">
    <h2>Take the Tour</h2>
     <!--<iframe title="YouTube video player" class="youtube-player" type="text/html" 
width="100%" height="720" src="https://www.demochimp.com/app/view/p/3g5k5d3c"
frameborder="0" allowFullScreen></iframe>-->
  </div>
  <div class="ft-content why-dm-ctr clearfix">
    <h2>Why Choose doctors?</h2>
    <div class="ftbox boxgreen" style="padding-top: 5px;">
      <figure><img src="images/ft-01.png" alt=""></figure>
      <p>Patients can find the right doctor for their needs by searching by insurance, speciality, location, gender, or languages spoken.</p><p>They can also see verified reviews, doctor qualifications, photos of the doctors &amp; their facilities.</p>
    </div>
    <div class="ftbox boxblue" style="padding-top: 5px;">
      <figure><img src="images/ft-02.png" alt=""></figure>
      <p>Most doctors patients see a doctor in 24 – 72 hours, which is much faster than the average three week wait time patients experience across the US.</p><p>doctors also sends email and text message reminders about upcoming appointments.</p>
    </div>
    <div class="ftbox boxorange" style="padding-top: 5px;">
      <figure><img src="images/ft-03.png" alt=""></figure>
      <p>doctors reveals a hidden supply of medical appointments including the 10 to 20 percent of appointments that are cancelled last-minute and makes these time slots instantly available to patients.</p>
    </div>
  </div>
  
  <div class="buzz-area clearfix">
    <h2>Who's Buzzing About Us?</h2>
    <ul>
      <li><img src="images/tech-coctail.png" alt=""></li>
      <li><img src="images/cbso.png" alt=""></li>
      <li><img src="images/challenge-cup.png" alt=""></li>
      <li><img src="images/aarp.png" alt=""></li>
      <li><img src="images/business-rockstars.png" alt=""></li>
    </ul>
  </div>
</div>
<!-- /CONTENT SECTION -->
