<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<div class="white-bg contactblock-gap clearfix">
				<div class="contact-left">
					<div class="contact-map">
						<img src="/images/contact-map.png" alt="map" class="fullimg">
					</div>
					<div class="headline">
						<h2>Some Information</h2>
					</div>
					<p>We are committed to help you manage your health online!<br>
					Please fill out the form and we will get back to you soon.</p>
					<div class="headline">
						<h2>How can we help?</h2>
					</div>
					<form name="emailForm" method="post" >
						<div class="form-row clearfix">
							<div class="left">
								<p><label>Name <span class="required">*</span></label></p>
								<?php echo $this->form->first_name; ?>									
							</div>
							<div class="right">
								<p><label>E-Mail <span class="required">*</span></label></p>
								<?php echo $this->form->email; ?>
							</div>
						</div>
						<div class="form-row clearfix">
							<p><label>Subject <span class="required">*</span></label></p>
							<?php echo $this->form->subject; ?>
						</div>
						<div class="form-row clearfix">
							<p><label>Message <span class="required">*</span></label></p>
							<?php echo $this->form->enquiry; ?>
						</div>
						<div class="form-row clearfix">
							<input name="Submit" type="submit" value="Submit" id="sendSupportForm">
						</div>
					</form>
					<div id="supportForm"></div>
				</div>
				<div class="contact-right">
					<div class="block-box">
						<div class="content">
							<h3>BUSINESS HOURS</h3>
                            <p class="contacttext">Support is available Monday through Saturday: <span>(888) 508-5778</span></p>
							<p class="contacttext"><span>Monday-Friday:</span> 8am to 6pm</p>
							<p class="contacttext"><span>Saturday:</span> 9am to 1pm</p>
							<p class="contacttext"><span>Sunday:</span> Closed</p>
						</div>
					</div>
					<div class="block-box nb">
						<div class="content">
							<h3>Contact Information</h3>
							<p class="contacttext large"><img src="images/phone-icon.png" alt="phone">Phone: <span>(888) 508-5778</span></p>
							<p class="contacttext large"><img src="images/fax-icon.png" alt="fax">Fax: <span> <span>(949) 424-8919</span></p>
							<p class="contacttext large"><img src="images/mail-icon.png" alt="mail">Email: <script type="text/javascript" language="javascript">
                                    <!--
                                    // Email obfuscator script 2.1 by Tim Williams, University of Arizona
                                    // Random encryption key feature by Andrew Moulden, Site Engineering Ltd
                                    // This code is freeware provided these four comment lines remain intact
                                    // A wizard to generate this code is at http://www.jottings.com/obfuscator/
                                    { coded = "JfVVHLZ@KH1N9ZC.1HN"
                                        key = "MjgrPsytY8VIlmRG5Q7ndeLXJDZcu2qSNOi6voaKCAkbT31fw4EUBpWxH90hzF"
                                        shift=coded.length
                                        link=""
                                        for (i=0; i<coded.length; i++) {
                                            if (key.indexOf(coded.charAt(i))==-1) {
                                                ltr = coded.charAt(i)
                                                link += (ltr)
                                            }
                                            else {
                                                ltr = (key.indexOf(coded.charAt(i))-shift+key.length) % key.length
                                                link += (key.charAt(ltr))
                                            }
                                        }
                                        document.write("<a href='mailto:"+link+"'>"+link+"</a>")
                                    }
                                    //-->
                                </script><noscript>Sorry, you need Javascript on to email me.</noscript>
                            </p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	jQuery("#sendSupportForm").click(function(event){
		event.preventDefault();
		var first_name = jQuery("#first_name").val();
		var email = jQuery("#email").val();
		var subject = jQuery("#subject").val();
		var enquiry = jQuery("#enquiry").val();

		$.post("/index/send-contact", {first_name:first_name, email:email, subject:subject, enquiry:enquiry },
			function(html){			
				jQuery("#supportForm").append(html);
				jQuery("#first_name").val("");
				jQuery("#email").val("");
				jQuery("#subject").val("");
				jQuery("#enquiry").val("");
			}
		);
	});
});
</script>