<?php echo $this->render("search/searchbox.phtml"); ?>

<div class="book-process-box">
  <h2>Book your Doctor and Dentist <br />
    <span>Appointment Online, It's Free!</span></h2>
  <div class="step"><img src="images/step1.png" alt="View and choose Available Time" align="left" /><img src="images/step2.png" alt="View and choose Available Time" align="left" /><img src="images/step3.png" alt="View and choose Available Time" align="left" /></div>
  <div class="process-box first">
    <h3>Find a Doctor or <br  />
      Dentist</h3>
    <img src="images/process1.png" alt="Seasch for a Doctor or Dentist" />
    <div class="process-arrow"></div>
  </div>
  <div class="process-box">
    <div class="pad">
      <h3>View Available <br  />
        Times</h3>
      <img src="images/process2.png" alt="View and choose Available Time" />
      <div class="process-arrow"></div>
    </div>
  </div>
  <div class="process-box last">
    <h3>Book Your <br />
      Appointment</h3>
    <img src="images/process3.png" alt="Book Appointment It's Free" /></div>
  <div class="clear"></div>
  <h4>SAVE up to 50% off*<br />
    Your first office visit, <a href="/dentist-new-york">Book Now!</a></h4>
</div>
<div class="clear"></div>
<div class="patient-comment">
  <h2>Patient Comments</h2>
  <div class="comment-box">
    <div class="comment-box-top"><img border="0" src="/images/spacer.gif"></div>
    <div class="comment-box-middle">
      <div class="comment-txt">I love this website! Meeting my Doctor on video first helped me choose the Doctor that is right for me. Plus, I was even able to save on my first visit.<span><img border="0" alt="Quote" src="/images/quote-right.png"></span>
        <div class="comment-by">Sarah W</div>
      </div>
    </div>
    <div class="comment-box-bottom"><img border="0" src="/images/spacer.gif"></div>
  </div>
  <div class="comment-box">
    <div class="comment-box-top"><img border="0" src="/images/spacer.gif"></div>
    <div class="comment-box-middle">
      <div class="comment-txt">I recently moved and needed a new Dentist. This site helped me find a Dentist that accepts my insurance. I was able to book an appointment instantly!<span><img border="0" alt="Quote" src="/images/quote-right.png"></span>
        <div class="comment-by">Paul S</div>
      </div>
    </div>
    <div class="comment-box-bottom"><img border="0" src="/images/spacer.gif"></div>
  </div>
</div>
<div class="home-article-scroll">
  <h2 class="article-title">Meet The Top Doctors and Dentists of 2011</h2>
  <div class="article-data">
  <div class="art-det">
  <div class="det-top"></div>
  <div class="matter">
    <h3>2011 Top Doc Award Winners Featured on a Television Commercial Segment on FOX Airing During The Dr. Oz Show</h3>
    <p class="watch">New segments premiere every week</p>
<p class="links">Watch now, <a href="/watch-video/watch-video">click here</a></p><br />
    </div>
     <div class="det-bot"></div>
    </div>
    <br clear="all" />
    <br />
    <br />
    <div class="art-det">
  <div class="det-top"></div>
  <div class="matter">
    <h3>Meet Your Doctor and Dentist On-Demand<br />
Through XFINITY TV Available From Comcast</h3>
    <p class="watch">View profile videos on television available 24/7</p>
    <p class="links">Learn more, <a href="comcast">click here</a></p>
    </div>
<div class="det-bot"></div>
    </div>
    <br />
    <br />
  </div>
</div>
