<div class="container">
    	<div class="row">
        	<div class="col-sm-12">
            	<div class="container-inner white-bg">
					<!-- CONTENT SECTION -->
					<!--FIVERBOX -->
					<div class="fourbox extra-div-space clearfix lazy-load-box effect-zoomin">
						<div class="box01 green-grad border-radius-small">
					    	<a href="#"><img src="/images/social-campaign-icon.png" alt="Social Campaign"></a>
					        <h2><a href="#">SOCIAL <br> CAMPAIGNS</a></h2>
					    </div>
					    <div class="box01 skyblue-grad border-radius-small">
					    	<a href="#"><img src="/images/patient-refer-icon.png" alt="Patient Referals"></a>
					        <h2><a href="#">PATIENT <br> REFERRALS</a></h2>
					    </div>
					    <div class="box01 orange-grad border-radius-small">
					    	<a href="#"><img src="/images/automated-communication-icon.png" alt="Automated Communication"></a>
					        <h2><a href="#">AUTOMATED <br> COMMUNICATION</a></h2>
					    </div>
					    <div class="box01 yellow-grad border-radius-small">
					    	<a href="#"><img src="/images/satisfaction-survey-icon.png" alt="Satifaction Survey"></a>
					        <h2><a href="#">SATISFACTION <br> SURVEYS</a></h2>
					    </div>
					    <div class="box01 blue-grad border-radius-small">
					    	<a href="#"><img src="/images/online-appoinment-icon.png" alt="Online Appointment"></a>
					        <h2><a href="#">ONLINE <br> APPOINTMENTS</a></h2>
					    </div>
					</div>
					<!--/FIVEBOX -->
					<h2 class="sub-heading text-center">What <img src="/images/doctors-logo.png" alt="doctors"> Does?</h2>
					<!--FIVEBOX -->
					<div class="fivebox lazy-load-box effect-zoomin">
						<div class="box01 green-grad border-radius-small lazy-load-box effect-zoomin">
					    	<div class="container-fluid">
					        	<div class="row">
					            	<div class="col-sm-3">
					                	<div class="serv-box">
					                	<a href="#"><img src="/images/social-campaign-icon.png" alt="Social Campaign"></a>
					        			<h2><a href="#">SOCIAL <br> CAMPAIGNS</a></h2>
					                    </div>
					                </div>
					                <div class="col-sm-9">
					                	<div class="service-brief">
					                    	<h3><a href="#">HAVE A POSITIVE PRESENCE ONLINE. <span>Social Campaigns</span></a></h3>
					                        <ul>
					                        	<li>You can post or schedule posts for a later date which post to your social media profiles online</li>
					                            <li>Patients can request an appointment with you through your facebook page</li>
					                        </ul>
					                    </div>
					                </div>
					            </div>
					        </div>
					    </div>
					    <div class="box01 skyblue-grad border-radius-small lazy-load-box effect-zoomin">
					    	<div class="container-fluid">
					        	<div class="row">
					            	<div class="col-sm-3">
					                	<div class="serv-box">
					                	<a href="#"><img src="/images/patient-refer-icon.png" alt="Patient Referals"></a>
					        			<h2><a href="#">PATIENT <br> REFERRALS</a></h2>
					                    </div>
					                </div>
					                <div class="col-sm-9">
					                	<div class="service-brief">
					                    	<h3><a href="#">GROW YOUR PRACTICE: <span>Patient Referrals</span></a></h3>
					                        <ul>
					                        	<li>First, the customer visits your business.</li>
					                            <li>Next, our Referral manager sends an automated email, asking them to refer their friends &amp; family.</li>
					                        </ul>
					                    </div>
					                </div>
					            </div>
					        </div>
					    </div>
					    <div class="box01 orange-grad border-radius-small lazy-load-box effect-zoomin">
					    	<div class="container-fluid">
					        	<div class="row">
					            	<div class="col-sm-3">
					                	<div class="serv-box">
					                	<a href="#"><img src="/images/automated-communication-icon.png" alt="Automated Communication"></a>
					        			<h2><a href="#">AUTOMATED <br> COMMUNICATION</a></h2>
					                    </div>
					                </div>
					                <div class="col-sm-9">
					                	<div class="service-brief">
					                    	<h3><a href="#">BRING THEM BACK: <span>Automated Communication</span></a></h3>
					                        <ul>
					                        	<li>Personalized recall messages</li>
					                            <li>Bring clients back with tailored communication</li>
					                        </ul>
					                    </div>
					                </div>
					            </div>
					        </div>
					    </div>
					    <div class="box01 yellow-grad border-radius-small lazy-load-box effect-zoomin">
					    	<div class="container-fluid">
					        	<div class="row">
					            	<div class="col-sm-3">
					                	<div class="serv-box">
					                	<a href="#"><img src="/images/satisfaction-survey-icon.png" alt="Satifaction Survey"></a>
					        			<h2><a href="#">SATISFACTION <br> SURVEYS</a></h2>
					                    </div>
					                </div>
					                <div class="col-sm-9">
					                	<div class="service-brief">
					                    	<h3><a href="#">KNOW WHAT THEIR SAYING: <span>Satisfaction Surveys</span></a></h3>
					                        <ul>
					                        	<li>doctors allows you to monitor and respond to all of your certified reviews instantly all from one place</li>
					                            <li>Gauge how your practice is performing and how to make it better</li>
					                        </ul>
					                    </div>
					                </div>
					            </div>
					        </div>
					    </div>
					    <div class="box01 blue-grad border-radius-small lazy-load-box effect-zoomin">
					    	<div class="container-fluid">
					        	<div class="row">
					            	<div class="col-sm-3">
					                	<div class="serv-box">
					                	<a href="#"><img src="/images/online-appoinment-icon.png" alt="Online Appointment"></a>
					        			<h2><a href="#">ONLINE <br> APPOINTMENTS</a></h2>
					                    </div>
					                </div>
					                <div class="col-sm-9">
					                	<div class="service-brief">
					                    	<h3><a href="#">YOUR PRACTICE OPEN. 24 HOURS:<span>Satisfaction Surveys</span></a></h3>
					                        <ul>
					                        	<li>Patients can book appointments with you 24 hours a day 7 days a week</li>
					                        </ul>
					                    </div>
					                </div>
					            </div>
					        </div>
					    </div>
					</div>
					<!--/FIVEBOX -->
					<h2 class="sub-heading text-center">How <img src="/images/doctors-logo.png" alt="doctors"> Work?</h2>
				
					<div class="grey-grad text-center lazy-load-box effect-zoomin">
						<img src="/images/top-grey-graphics.png" alt="doctors">
						<div class="four-serv clearfix">
							<div class="box green-grad">
						    	<a href="#"><img src="/images/serv01.png" alt="doctors"></a>
						        <p>doctors is the Directory &amp; Network used by employers and cash patients</p>
						    </div>
						    <div class="box skyblue-grad">
						    	<a href="#"><img src="/images/serv02.png" alt="doctors"></a>
						        <p>Members use doctors portal to select a doctor that best suits their needs</p>
						    </div>
						    <div class="box orange-grad">
						    	<a href="#"><img src="/images/serv03.png" alt="doctors"></a>
						        <p>Patient requests appointments 24/7 through doctors calendar sync technology</p>
						    </div>
						    <div class="box yellow-grad">
						    	<a href="#"><img src="/images/serv04.png" alt="doctors"></a>
						        <p>Informed patient arrives at office eager to begin treatment, and pays at point of service</p>
						    </div>
						</div>

						<p class="bigblue-text">doctors patients are engaged and satisfied with their experience.</p>
						<p class="normal-text extra-textpadding">doctors leverages technology to educate our members about their dental health and doctors providers. 
						Everything we do is designed to bring patients to your door.</p>
						</div>
						<div class="white-bg number-count lazy-load-box effect-zoomin">
						<div class="container-fluid">
							<div class="row">
						    	<div class="col-sm-1"></div>
						        <div class="col-sm-5">
						        	<div class="container-fluid">
						            	<div class="row">
						                	<div class="col-sm-4">
						                    	<div class="full-cir grey-grad">40%
						                        </div>
						                    </div>
						                    <div class="col-sm-8">
						                    	<div class="number-text border-radius-small">
						                        	of doctors members schedule immediate follow up after first visit
						                        </div>
						                    </div>
						                </div>
						            </div>
						        </div>
						        
						        <div class="col-sm-5">
						        	<div class="container-fluid">
						            	<div class="row">
						                	<div class="col-sm-4">
						                    	<div class="full-cir grey-grad">90%
						                        </div>
						                    </div>
						                    <div class="col-sm-8">
						                    	<div class="number-text border-radius-small">
						                        	of doctors members recommend doctors to their friends and family
						                        </div>
						                    </div>
						                </div>
						            </div>
						        </div>
						        <div class="col-sm-1"></div>
						    </div>
						</div>
						</div>
						<div class="buzzina-area lazy-load-box effect-zoomin">
						<h3>Who’s Buzzing About Us?</h3>
						<ul>
							<li><a href="#"><img src="/images/logo01.png" alt="logo"></a></li>
						    <li><a href="#"><img src="/images/logo02.png" alt="logo"></a></li>
						    <li><a href="#"><img src="/images/logo03.png" alt="logo"></a></li>
						    <li><a href="#"><img src="/images/logo04.png" alt="logo"></a></li>
						    <li><a href="#"><img src="/images/logo05.png" alt="logo"></a></li>
						</ul>
						</div>
						<div class="white-bg clearfix lazy-load-box effect-zoomin">
						<div class="blue-btn skyblue-grad border-radius-small text-center">
							<a href="#">Call Us Today at <span>1 (800) 974-5065</span></a>
						</div>
						</div>
						<div class="bottom-green-grad lazy-load-box effect-zoomin">
						<div class="text-block text-center">
							<p>Partner With Us To Grow 
						Your Practice Starting Today</p>
						</div>
						</div>
						<div class="white-bg four-section clearfix lazy-load-box effect-zoomin">
						<div class="box01">
							<img src="/images/icon01.png" alt="doctors">
						    <h3><a href="#">Convenience</a></h3>
						    <p>Our service and online tool will help bring new patients to your door</p>
						</div>
						<div class="box02">
							<img src="/images/icon02.png" alt="doctors">
						    <h3><a href="#">Control</a></h3>
						    <p>Create your own schedule</p>
						</div>
						<div class="box03">
							<img src="/images/icon03.png" alt="doctors">
						    <h3><a href="#">Recognition</a></h3>
						    <p>Create robust online profile, highlighting your practice as one of the best</p>
						</div>
						<div class="box04">
							<img src="/images/icon04.png" alt="doctors">
						    <h3><a href="#">Growth</a></h3>
						    <p>Thousands of members will now be able to choose you as their new doctor</p>
						</div>
						</div>
						<div class="yellow-grad bottom-text text-center lazy-load-box effect-zoomin">
						<p class="bluetext">Reduce administrative overheads</p>
						<p class="blacktext">Reduce call volume to your practice and free up admin time. No more long waits on the phone for your patients</p>
						<div class="callus">Call Us Today at 1 (800) 974-5065</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>