<!--BANNER SECTION -->
	<div class="banner-section effect-zoomin" style="padding-top:40px;padding-bottom:40px;">
    		<div class="container">
            	
                <div class="manage-your-health" style="margin-top:0px;margin-bottom:0px;">
                	<div class="manage-left" style="padding-bottom:20px;">
                    	<h6>Grow <span>Your Practice</span> With <span>doctors</span> </h6>
                        <p>doctors is a service that helps patients and doctors communicate in a very rich experience through the doctors online platform.</p>
                        
                    </div>
                    <div class="manage-right">
                    	<a href="/register" class="get-start">GET STARTED NOW!</a>
                    </div>
					<a href="#bottom1" class="arrows-one" id="top1" style="padding-top:10px;padding-bottom:0px;"> <img src="images/arrows.png" alt=""> </a>
                </div>
            </div>
        
    </div>
<!--/BANNER SECTION -->
<!--CONTAINER SECTION -->
<div class="middle">
	<div class="container">
    	<div class="row">
        	<div class="col-sm-12">
            <div class="pannel" id="bottom1">
            	<!--<h2>How doctors Helps you?</h2>-->
				<!--<iframe title="YouTube video player" class="youtube-player" type="text/html" 
				width="100%" height="720" src="https://www.demochimp.com/app/view/p/3g5k5d3c"
				frameborder="0" allowFullScreen></iframe> -->

                        <!--        <iframe width="560" height="315" src="https://www.youtube.com/embed/fEGdFOWgn4U?list=PLNjHzZlaO7f8RuMdD_cU7KrkFfjk7HjuI" frameborder="0" allowfullscreen></iframe>
                            -->
<iframe title="YouTube video player" class="youtube-player" type="text/html"
                                width="100%" height="720" src="https://www.youtube.com/embed/fEGdFOWgn4U?list=PLNjHzZlaO7f8RuMdD_cU7KrkFfjk7HjuI"
                                frameborder="0" allowFullScreen></iframe>     
                <div class="main-pannel-top lazy-load-box effect-zoomin clearfix">
                	<div class="pannel-left">
                    	<h5>Patient Reviews:</h5>
                        <p>Write reviews about your doctors online! You can rate your doctors by: Wait Time, Bedside Manner, and Overall Experience.</p>
                    </div>
                    <div class="pannel-right">
                    	<img src="images/red-ribben.png" alt="">
                    </div>
                </div>
                
                <div class="main-pannel-bottom lazy-load-box effect-zoomin clearfix">
                	<div class="pannel-left right-para">
                    	<h5>Secure Messaging:</h5>
                        <p>Send and receive Secure Messages to and from your doctors anytime of the day.  Have a question about a blood test report or billing? Send a secure message through our HIPAA compliant platform. </p>
                    </div>
                    <div class="pannel-right left-image">
                    	<img src="images/stars.png" alt="">
                    </div>
                </div>
                
                <div class="main-pannel-top lazy-load-box effect-zoomin clearfix">
                	<div class="pannel-left">
                    	<h5>Medical Expenses:</h5>
                        <p>Keep track of all of your medical expenses through doctors.  You can manage upcoming medical bills and past due bills using the medical expenses feature! </p>
                    </div>
                    <div class="pannel-right">
                    	<img src="images/3.png" alt="">
                    </div>
                </div>
                
                <div class="main-pannel-bottom lazy-load-box effect-zoomin clearfix">
                	<div class="pannel-left right-para">
                    	<h5>Medical History:</h5>
                        <p>Enter your Medical History information on our secure HIPAA compliant website and you can share it with a click of a button with any doctor you like so you don’t have to fill in new patient paperwork every time you go to a new doctor! </p>
                    </div>
                    <div class="pannel-right left-image">
                    	<img src="images/4.png" alt="">
                    </div>
                </div>
                
                <div class="main-pannel-top lazy-load-box effect-zoomin clearfix">
                	<div class="pannel-left">
                    	<h5>Favorite Doctors:</h5>
                        <p>Keep your family of doctors in one place.
                            Access your doctors, appointments, messaging, reviews etc all on doctors!  </p>
                    </div>
                    <div class="pannel-right">
                    	<img src="images/5.png" alt="">
                    </div>
                </div>
                
                <div class="main-pannel-bottom lazy-load-box effect-zoomin clearfix">
                	<div class="pannel-left right-para">
                    	<h5>Referrals:</h5>
                        <p>You can refer your friends and family to your favorite doctors and in return earn points to buy goodies online! </p>
                    </div>
                    <div class="pannel-right left-image">
                    	<img src="images/6.png" alt="">
                    </div>
                </div>
                
                <a href="#bottom2" class="bottom-arrows" id="top2"> <img src="images/arrow-show-bottom.png" alt=""> </a>
                
              	<div class="main-pannel-top bookapponts lazy-load-box effect-zoomin clearfix" id="bottom2">
                	<div class="pannel-left appointments">
                    	<h5>Book Appointments </h5>
                        <span>Online With Your Favorite Doctor 24/7 </span>
                        <p>You can search for any type of specialty and book 
live appointments online all day every day.   </p>
                    </div>
                    <div class="pannel-right">
                    	<img src="images/last.png" alt="">
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>

<div class="banner-section lazy-load-box effect-zoomin">
	<div class="container">
		
		<?php echo $this->render("/search/search.phtml"); ?>
		
	 </div>
	
</div>

<!-- whos buzzing start here -->
<div class="main-buzzing lazy-load-box effect-zoomin">
	<div class="container">
    	<div class="row">
        	<div class="col-sm-12">
            <h2>Who’s Buzzing</h2>
            <span>About Us?</span>
            <img src="images/logo1.png" alt="">
            <img src="images/logo2.png" alt="">
            <img src="images/logo3.png" alt="">
            <img src="images/logo4.png" alt="">
            <img src="images/logo5.png" alt="">
            </div>
        </div>
    </div>
</div>

<!-- whos buzzing end here -->

<!-- have questions start here -->
<div class="havequestion lazy-load-box effect-zoomin">
	<div class="container">
    	<div class="row">
        	<div class="col-sm-12">
            	<p class="our-services">Our Service Is Free For Patients and available to you around the clock. </p>
                <h4 class="ques">Have Questions?</h4>
                <div class="calls-us">
                	<img src="images/tel-icon.png" alt="">
                    <span>Call Us at: (888) 508-5778</span>
                </div>
                
                <div class="calls-us">
                	<img src="images/message-icon.png" alt="">
                    <span>Email us at: service@doctors.com  </span>
                </div>
            </div>
        </div>
    </div>
</div>
	<script>
	jQuery(document).ready(function() {
	
$('a[href^="#"]').on('click', function(event) {

    var target = $( $(this).attr('href') );

    if( target.length ) {
        event.preventDefault();
        $('html, body').animate({
            scrollTop: target.offset().top
        }, 1000);
    }

});

 });
	</script>
