<script>
// code for add product image dynamically
var count = 2;
function addRow(divId) {
    // create a div dynamically
    var parentDiv = document.getElementById(divId);
   // create a div dynamically
    var eleDiv = document.createElement("div");
    eleDiv.setAttribute("name", "dataTable"+count);
    eleDiv.setAttribute("id", "dataTable"+count);
    eleDiv.setAttribute("class", "grey-content clearfix");
    eleDiv.setAttribute("style", "width:100%");

    eleDivinner= document.createElement("div");
    eleDivinner.setAttribute("style", "width:100%;float:left;");
    eleDivinner.setAttribute("id", "innerdiv");

    msgdiv= document.createElement("div");
    msgdiv.setAttribute("id", "msgdiv"+count);
     // create a textbox dynamically
    var eleText = document.createElement("input");
    eleText.setAttribute("type", "text");
    eleText.setAttribute("tabindex", "1");
    eleText.setAttribute("name", 'first_name[]');
	eleText.setAttribute("style", "float:left;" )
    eleText.setAttribute("id", "first_name[]");
    eleText.setAttribute("class", "preg-txt");
	eleText.setAttribute("placeholder", "First Name");
    eleText.setAttribute("float", "left");
    eleText.setAttribute("style", "width:45%;float:left;margin-left:15px;");

    var emailField = document.createElement("input");
    emailField.setAttribute("type", "text");
    emailField.setAttribute("tabindex", "8");
    emailField.setAttribute("name", 'email[]');
    emailField.setAttribute("id", "email[]");
    emailField.setAttribute("class", "preg-txt");
	emailField.setAttribute("placeholder", "E mail");
    emailField.setAttribute("float", "left");
    emailField.setAttribute("style", "width:45%;float:left;margin-left:15px;");


    var phoneField = document.createElement("input");
    phoneField.setAttribute("type", "text");
    phoneField.setAttribute("tabindex", "1");
    phoneField.setAttribute("name", 'phone_no[]');
    phoneField.setAttribute("id", "phone_no[]");
    phoneField.setAttribute("class", "preg-txt");
	phoneField.setAttribute("placeholder", "Phone no.");
	phoneField.setAttribute("float", "left");
    phoneField.setAttribute("style", "width:45%;float:left;margin-left:15px;");
     
    var notesField = document.createElement("input");
    notesField.setAttribute("type", "text");
    notesField.setAttribute("tabindex", "1");
    notesField.setAttribute("name", 'imp_notes[]');
    notesField.setAttribute("id", "imp_notes[]");
    notesField.setAttribute("class", "preg-txt");
	notesField.setAttribute("placeholder", "Important Notes :");
    notesField.setAttribute("float", "left");;
    notesField.setAttribute("style", "width:45%;float:left;margin-left:15px;");

     var cancelBtn = document.createElement("input");
    cancelBtn.setAttribute("type", "button");
    cancelBtn.setAttribute("name", 'cancelbtn');
    cancelBtn.setAttribute("id", 'cancelbtn');
    cancelBtn.setAttribute("value", 'remove');
    cancelBtn.setAttribute("class", 'glyphicon glyphicon-remove');
    cancelBtn.setAttribute("style", 'margin-left:7px;margin-top:30px;');
	cancelBtn.setAttribute("onclick" , "deleteRow("+count+")" );

	
   var submitBtn = document.createElement("input");
    submitBtn.setAttribute("type", "button");
    submitBtn.setAttribute("name", 'submitbtn'+count);
    submitBtn.setAttribute("id", 'submitbtn'+ count);
    submitBtn.setAttribute("class", 'blue-btn');
    submitBtn.setAttribute("value" , "Submit" )
	submitBtn.setAttribute("onclick" , "formprocess"+count+"()" )

    document.getElementById('count_option').value=count;
    // append new div to parent div
    eleDivinner.appendChild(eleText);
    eleDiv.appendChild(msgdiv); 
    eleDiv.appendChild(eleDivinner); 

    parentDiv.appendChild(eleDiv);
     // append textbox & button to new div 
	 eleDivinner.appendChild(emailField);
	 eleDivinner.appendChild(phoneField);
	 eleDivinner.appendChild(notesField);
	 eleDivinner.appendChild(cancelBtn);
    // eleDivinner.appendChild(submitBtn);
    ++count;
}
function deleteRow(count) {
       var div = document.getElementById('dataTable'+count);
        if (div) {
            div.remove(div);
           $("#msgdiv").html("<span style='color:#EF422D;'>Row deleted successsfully</span>"); 
        }
}
</script>
<div class="container">
	<div class="row">
    	<div class="col-sm-12">
    		<form id="loginForm" name="login" method="post" action="<?php echo $this->form->action ?>">
	           <div class="white-bg patient-registration clearfix">
	            	<div class="container-fluid">
	                	<div class="row">
	                	<?php 
                            if($this->msg=='diff1'){ echo "<div style='color:#EF422D;padding-left:50px;'>Duplicate Referral Email Id Not Allow.</div>" ; }
                            if($this->msg=='diff2'){ echo "<div style='color:#EF422D;padding-left:50px;'>New  Referral Added Successfully.</div>" ; } 
                            if($this->msg=='diff3'){ echo "<div style='color:#EF422D;padding-left:50px;'>Each referral Email Id should be unique </div>" ; } 
                            ?>
	                    	<div class="col-sm-12">
	                        	<h2>Patient referrals to the doctor With doctors </h2>
	                            <div class="full-border">
	                                 <div class="reg-pane">
		                            	<div class="container-fluid">
		                                	<div class="row">
		                                        <div class="col-sm">
		                                           <div id="patregstep1" style="min-height:100px;">
			                                        	<div class="grey-content clearfix" style="width:100%;" id='dataTable'>
			                                        		<div id="msgdiv"></div>
			                                        	   <div style="width:100%;float:left;;padding-left:13px;">
			                                               <?php echo $this->form->patient_id; ?>
                                                                       <?php echo $this->form->doctor_id; ?>    
                                                            
                                                                       <input type="text" placeholder="First Name" name="first_name[]" value="" tabindex="1" class="preg-txt" id="first_name[]" style="width:45%;float:left;margin-right:15px;">
			                                               <input type="text" placeholder="E Mail" name="email[]" value="" tabindex="8" class="preg-txt" id="email[]" style="width:45%;float:left;margin-right:15px;">
			                                                 <input type="text" placeholder="Phone no." name="phone_no[]" value="" tabindex="1" class="preg-txt" id="phone_no[]" style="width:45%;float:left;margin-right:15px;">
			                                                 <input type="text" placeholder="Important Notes :" name="imp_notes[]" value="" tabindex="1" class="preg-txt" id="imp_notes[]" style="width:45%;float:left;margin-right:15px;">

			                                               <!--  <input type="button" value="Submit" name="submitbtn" class="blue-btn" onclick="formprocess()">
			                                           -->
</div>
                                                      </div>
                                                 </div>
                                               </div>
		                                    </div>
		                                    <div class="col-sm">
													      <a class="blue-btn" id="reg_submit_btn" onclick="addRow('patregstep1')">+ More</a>
													      <a class="blue-btn" id="reg_submit_btn" onclick="formprocess()">Submit</a>
                                                          <input type="hidden" id="count_option" name="count_option" value="option">
										   </div>

		                                </div>
		                            </div>

		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
		        
	        </form>
        </div>
    </div>
</div>
<!--/CONTENT SECTION -->
<div id="error" style="display:none">
	<span id="errorMessage"></span>
</div>
<a href="#error" id="errorLauncher"></a>

<script language="javascript">//<![CDATA[
function formprocess(){


	    var first_name = document.getElementsByName('first_name[]');
	    var email =      document.getElementsByName('email[]');
	    var phone_no =   document.getElementsByName('phone_no[]');
	    var imp_notes =   document.getElementsByName('imp_notes[]');
	  for (var i=0; i<first_name.length; i++)
			{
    var namevalue = first_name[i].value ;
    var emailvalue = email[i].value ;
    var phone_novalue = phone_no[i].value;
	var imp_notevalue = imp_notes[i].value ;
	var doctor_id = $('#doctor_id'). val();
    var patient_id = $('#patient_id'). val();
      var  error_flag=0;
		var filter=/^.+@.+\..{2,3}$/ ;
        var error_msg = "<div id='errorbox' style='width:245px;'><h4><?php echo $this->lang[148]; ?></h4><ul id='errorList' style='padding-left:8px;'>";
		if(namevalue=="" )	{ error_msg += "<li><?php echo $this->lang[942]; ?></li>";	error_flag = 1; }
		if(emailvalue=="" )	{ error_msg += "<li><?php echo $this->lang[162]; ?></li>";	error_flag = 1; }
		else if(!filter.test(emailvalue))	{ error_msg += "<li><?php echo $this->lang[151]; ?></li>"; error_flag = 1; }
		if(phone_novalue=="")	{ error_msg += "<li><?php echo $this->lang[943]; ?></li>";	error_flag = 1; } 
		if(imp_notevalue=="")	{ error_msg += "<li><?php echo $this->lang[944]; ?></li>";	error_flag = 1; } 
		error_msg +="</ul></div>";
         }
	  if(error_flag==1) { 
			$("#errorMessage").html(""); //clean any previous messages
			$("#errorMessage").html(error_msg);
			$("#errorLauncher").fancybox({
				'width' : 250,
				'height' : 300,
				'autoScale' : true,
				'transitionIn' : 'none',
				'transitionOut' : 'none',
				'autoDimensionst' : false,
				'hideOnContentClick': true,
				'content': error_msg
			});
			$("#errorLauncher").click();
			$("#errorMessage").html(""); //clean any previous messages
			$("#errorMessage").html(error_msg);
			$("#errorLauncher").fancybox({
				'width' : 250,
				'height' : 300,
				'autoScale' : true,
				'transitionIn' : 'none',
				'transitionOut' : 'none',
				'autoDimensionst' : false,
				'hideOnContentClick': true,
				'content': error_msg
			});
			$("#errorLauncher").click();
	
		} else {
		    sendCode(first_name, email, phone_no,imp_notes,doctor_id,patient_id);
			window.scrollTo(0, 0);
		   }
 

}

function sendCode(first_name,email,phone_no,imp_notes,doctor_id,patient_id) {
    var namevalue = [];
    var emailvalue = [];
    var phone_novalue = [];
    var imp_notevalue = [];
    var doctor_id = $('#doctor_id'). val();
    var patient_id = $('#patient_id'). val(); 
    for (var i=0; i<first_name.length; i++)
	 {
        namevalue.push(first_name[i].value) ;
        emailvalue.push(email[i].value) ;
        phone_novalue.push(phone_no[i].value);
	    imp_notevalue.push(imp_notes[i].value) ;
    }
    $.post('/index/referrals-patient/', {
		pemail: emailvalue,
		fname: namevalue,
		phone_nos: phone_novalue,
		imp_notes: imp_notevalue,
		doctor_id: doctor_id,
		patient_id: patient_id,
	}, function(result){
            $('body').html(result);

                
      });
   
}

</script>
<style>
.blue-btn
{

    background: rgba(0, 0, 0, 0) url("/images/user/blue-btn-bg.png") repeat-x scroll center top;

    border: 1px solid #1ea1e6;

    border-radius: 6px;

    color: #fff;

    cursor: pointer;

    display: block;

    font-size: 18px;

    height: 38px;

    line-height: 38px;

    text-align: center;

    margin-top:10px;

    width:130px;
    margin-right: 292px;
    float:left;

}
</style>
