<?php $this->headLink()->appendStylesheet('/style/paginator.css'); ?>
<div id="pagination" class="clearfix">
	<div class="right">
	<!-- Previous page link -->
		<?php
		$actual_url= $this->url();
    
		$arrayLink=array();
		if(is_array($this->linkArray))
			$arrayLink=$this->linkArray;
        ?>
		<?php if (isset($this->previous)): ?>
			<a class="prevPageBtn" href="<?= $this->url(array_merge(array('page' => $this->previous),$arrayLink)); ?>"><span><?php echo $this->lang[0]; ?></span></a>
		<?php else: ?>
			<a class="prevPageBtn" href="#"><span class="disabled"><?php echo $this->lang[0]; ?></span></a>
		<?php endif; ?>
		<!-- Numbered page links -->
		<?php 
		$pagesCount=0;
		foreach ($this->pagesInRange as $page): 
			$pagesCount++;
			if ($page != $this->current): ?>
				<a href="<?= $this->url(array_merge(array('page' => $page),$arrayLink)); ?>"><span><?= $page; ?></span></a>
			<?php else: ?>
				<a href="#" class="selected_pag"><span class="current"><?= $page; ?></span></a>
			<?php endif; ?>
		<?php endforeach; 
		if($pagesCount==0) {
		?>
			<a href="#" class="selected_pag"><span class="current">1</span></a>
		<?php
		}
		?>				
		<!-- Next page link -->
		<?php if (isset($this->next)): ?>
				<a class="nextPageBtn" href="<?= $this->url(array_merge(array('page' => $this->next),$arrayLink)); ?>"><span><?php echo $this->lang[1]; ?></span></a>
		<?php else: ?>
				<a class="nextPageBtn" href="#"><span class="disabled"><?php echo $this->lang[1]; ?></span></a>
		<?php endif; ?>
	</div>
</div>	