<div class="inner_wrapperReg">
	<div id="searchHeaderReg" class="clearfix">
		<h1><?php echo $this->lang[48]; ?> <span><?php echo $this->lang[204]; ?></span></h1>		
	</div>
	<?php
	$total=0;
	foreach ($this->paginator as $obj) :	
		$total++;
	endforeach;
	$colsize = $total/3;
	$colsize = ceil($colsize);
	?>
	<div class="clearfix"  id="sitemapWrapper">
		<ul class="doc-sitemap-link left">
		<?php
		$i=0;
		foreach ($this->paginator as $obj) :
			if(($i%$colsize==0) && $i!=0) {
			?>
				</ul>
				<ul class="doc-sitemap-link left">		
			<?php
			}
			$real_url = "/search?search1={$obj->city}"; ?>
			<li><a href="<?php echo $this->seoUrl($real_url);?>"><?php echo $obj->city?></a></li>
		<?php $i++;
		endforeach;?>
		</ul>
	</div>	
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_sitemap.phtml'); ?>