<div class="inner_wrapperReg">
	<div id="searchHeaderReg" class="clearfix">
		<h1 class="left"><?php echo $this->lang[48]; ?> <span><?php echo $this->lang[210]; ?></span></h1>
	</div>
	<?php 
	$total=0;
	foreach ($this->paginator as $row){
		$total++;
	}
	$colsize = $total/3;
	$colsize = ceil($colsize);
	$i=0;
	?>
	<div class="clearfix"  id="sitemapWrapper">
		<ul class="doc-sitemap-link left">
			<?php 
			foreach ($this->paginator as $row) :
				if(($i%$colsize==0) && $i!=0){
				?>	
					</ul>
					<ul class="doc-sitemap-link left">
				<?php
				}
				 $real_url = "search?search1={$row->zipcode}";
			?>
			<li><a href="/search?<?php echo $this->lang[934]; ?>=<?php echo $row->zipcode;?>"><?php echo $row->zipcode;?></a></li>
			<?php
			$i++;
			endforeach;?>
		</ul>
	</div>	
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_sitemap.phtml'); ?>