 <style type="text/css">
    .td-date {text-align:center; vertical-align:top; background-color:#f2f2f2;font-size:12px; border: 1px solid #ccc;}
    .td-date div{width:90%; text-align:right;}
    .td-date-blank {text-align:center; vertical-align:top; background-color:#fff;}
</style>
<div id="admin-content-profile">
	<h2 class="profile-heading">Working hours</h2>
	<div class="profile-brief">
		<div class="container-fluid">
			<div class="row">
				<div class="auctor-new clearfix">
					<form name="frmSlot" id="frmSlot" action="/user/timeslot/index/" method="get">
						<div class="address03">
							<select name="month" id="month">
		                        <?php
		                        foreach ($this->monthArr as $m => $mName) {
		                            $sel = "";
		                            if ($m == $this->month)
		                                $sel = "selected='true'";
		                        	?>
		                        <option value='<?php echo $m; ?>' <?php echo $sel; ?>><?php echo $mName; ?></option><?php
		                        }
		                        ?>
		                    </select>
		                    <select name="year" id="year">
		                        <?php
		                        for ($y = date("Y"); $y <= (date("Y") + 1); $y++) {
		                            $sel = "";
		                            if ($y == $this->year)
		                                $sel = "selected='true'";
		                        ?>
		                            <option value='<?php echo $y; ?>' <?php echo $sel; ?>><?php echo $y; ?></option>
		                        <?php } ?>
		                    </select>
		                    <div class="numbersection"><input type="submit" value="Change month" name=""></div>
		                    <input type="hidden" name="drid" id="drid" value="<?php echo $this->docObject->getId(); ?>" />
		                </div>
	                </form>
				</div>
			</div>
		</div>
	</div>

	<div class="profile-brief">
		<div class="container-fluid">
			<div class="row">
				<div class="auctor-new clearfix">
					<div class="col-sm-12">
						<table width="100%" cellspacing="0" cellpadding="0" border="0" class="monthly-view">
							<tbody>
								<tr class="month-titlebar">
									<th class="month-title">Sunday</th>
									<th class="month-title">Monday</th>
									<th class="month-title">Tuesday</th>
									<th class="month-title">Wednesday</th>
									<th class="month-title">Thursday</th>
									<th class="month-title">Friday</th>
									<th class="month-title">Saturday</th>
								</tr>

		                    <?php
		                    $DoctorAppointment = new Application_Model_DoctorAppointmentCal();
		                    $TimeSlot = new Base_Timeslot();
		                    $isTrStart = false;
		                    $isTrEnd = false;
		                    $isBlank = true;
		                    $tdCtr = 0;
							
							for ($day = 1; $day <= date("t"); $day++) {
		                        $tdCtr++;
		                        if ($tdCtr % 7 == 1)
		                            $isTrStart = true;
		                        if ($tdCtr % 7 == 0)
		                            $isTrEnd = true;
		                        $slotDate = $this->year . "-" . $this->month . "-" . $day;
		                        $blankTd = date("w", strtotime($slotDate));

		                        //Set the monday as firstday of the week
		                        if ($blankTd == 0)
		                            $blankTd = 6;
		                        else
		                            $blankTd -= 1;

		                        if ($isTrStart) {
		                            echo "<tr>";
		                            $isTrStart = false;
		                        }
		                        if ($isBlank) {
		                            $isBlank = false;
		                            for ($loop = 0; $loop < $blankTd; $loop++) {
		                                $tdCtr++;
		                                echo "<td class='td-date-blank'>&nbsp;</td>";
		                            }
		                        }
		                        //######## Fetch slot data ##############
		                        $slotsAvailable = array();
		                        $isDeletedSlot = false;

		                        $object = $DoctorAppointment->fetchAll("doctor_id='{$this->docObject->getId()}' AND slot_date='{$slotDate}'", "slot_time");
		                        if ($object) {
									foreach ($object as $s => $slot) {
									    $slotsAvailable[] = date("H:i", strtotime($slotDate . " " . $slot->getSlotTime()));
									}
								}else{
									$isDeletedSlot = $TimeSlot->isDeletedSlot($this->docObject->getId(), $slotDate);
									if($isDeletedSlot===false){
									    $slotsAvailable = $TimeSlot->getDoctorTimeSlots($this->docObject->getId(), $slotDate);
									}
								}

		                        //######## Fetch slot data end ##############

		                        echo "<td class='td-date'>";

		                        if (strtotime($this->year . "-" . $this->month . "-" . $day) >= strtotime(date("Y-n-j"))) {
			                        $href = "/user/timeslot/edit/drid/" . $this->docObject->getId() . "/date/" . $this->year . "-" . $this->month . "-" . $day;
			                	    ?>
			                        <a href='<?php echo $href; ?>' style='display:block'><span class='datebox greenbox'><?php echo $day; ?></span>
			                        <?php if($isDeletedSlot) { // doctor delete the all slots for this date
			                        	echo '<div style="text-align:center;padding-top:50px;"><span>Deleted</span><br /></div>';
			                        } elseif (count($slotsAvailable)) {
			                            echo "<div><span>" . implode("</span><br />", $slotsAvailable) . "</div>";
									}?>
			                        </a>
			            	        <?php
		                        } else {
		                            echo "<span class='datebox bluebox'>" . $day . "</span>";
		                            if (count($slotsAvailable))
		                                echo "<div>" . implode("<br />", $slotsAvailable) . "</div>";
		                        }
		                            echo "</td>";
		                            if ($isTrEnd) {
		                                $isTrEnd = false;
		                                echo "</tr>";
		                            }
		                        }
		                    ?>
		                   	</tbody>
		                </table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
