<div class="table-container">
  <h2>Today's Booking - <span>Oct 26, 2010</span></h2>
  <table width="100%" cellspacing="0" cellpadding="0" border="0" align="center" class="appointment-table-heading">
    <tbody>
      <tr>
        <th width="20%">Patient</th>
        <th width="20%">Email</th>
        <th width="20%" style="padding-left: 10px;">Date</th>
        <th width="20%" style="padding-left: 10px;">Details</th>
        <th width="20%" style="padding-left: 10px;">Status</th>
      </tr>
    </tbody>
  </table>
  <div class="sidescroll">
    <table width="100%" cellspacing="0" cellpadding="0" border="0" align="center" class="appointment-table">
      <tbody>
        <tr>
          <td>No Appointment!</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
