<div class="pagination">
    <div>
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->first)); ?>"><?php echo $this->lang[282]; ?></a> |
        <?php else: ?>
                <span class="disabled"><?php echo $this->lang[282]; ?></span> |
        <?php endif; ?>
    
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; <?php echo $this->lang[0]; ?></a> |
        <?php else: ?>
            <span class="disabled">&lt; <?php echo $this->lang[0]; ?></span> |
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
            <?php else: ?>
                <?= $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
              | <a href="<?= $this->url(array('page' => $this->next)); ?>"><?php echo $this->lang[1]; ?> &gt;</a> |
        <?php else: ?>
            | <span class="disabled"><?php echo $this->lang[1]; ?> &gt;</span> |
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
              <a href="<?= $this->url(array('page' => $this->last)); ?>"><?php echo $this->lang[283]; ?></a>
        <?php else: ?>
            <span class="disabled"><?php echo $this->lang[283]; ?></span>
        <?php endif; ?>
        &nbsp; <?php echo $this->lang[537]; ?> <?= $this->current; ?> <?php echo $this->lang[538]; ?> <?= $this->last; ?>
    </div>
 </div>