<?php echo $this->doctype() ?>
<html lang="en">
  <head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
	<link rel="icon" href="/images/favicon.ico" type="image/x-icon">
<?php    
        echo $this->headTitle();
        echo $this->headMeta();
		$this->headLink()->appendStylesheet('/style/search/default.css');
		$this->headLink()->appendStylesheet('/style/search/bootstrap.css');
		$this->headLink()->appendStylesheet('/style/search/style.css');
		$this->headLink()->appendStylesheet("/js/autosuggest/jquery.autocomplete.css");
		?>
		<!--[if IE]><script src="js/html5.js"></script><![endif]-->
		<?php
        $this->headLink()->appendStylesheet('/style/search/nivo-slider.css');
		$this->headLink()->appendStylesheet('/style/search/lazy-load.css');
		$this->headLink()->appendStylesheet('/style/search/meanmenu.css');
		$this->headLink()->appendStylesheet('/style/search/bootstrap-responsive.css');
		$this->headLink()->appendStylesheet('/style/search/bootstrap-theme.css');
		$this->headLink()->appendStylesheet('/style/search/demo.css');
		$this->headLink()->appendStylesheet('/style/app-scr.css');
		$this->headLink()->appendStylesheet('/js/fancybox/jquery.fancybox-1.3.4.css');
				
        echo $this->headLink(); 
		$this->headScript()->appendFile('/js/jquery-1.7.1.min.js'); 
        $this->headScript()->appendFile('/js/hover.js');
		$this->headScript()->appendFile('/js/jquery.flexisel.js'); 
		$this->headScript()->appendFile('/js/smoothscroll.js'); 
		$this->headScript()->appendFile("/js/autosuggest/jquery.autocomplete.min.js");
		$this->headScript()->appendFile("https://maps.googleapis.com/maps/api/js?libraries=places&sensor=false&language=en");
		$this->headScript()->appendFile("/js/jquery.accordion.js");
		$this->headScript()->appendFile("/js/highlight.pack.js");
		$this->headScript()->appendFile("/js/jquery.json-2.2.js");
		$this->headScript()->appendFile("/js/jqtransform/jquery.jqtransform.js");
		$this->headScript()->appendFile("/js/jquery.blockUI.js");
		$this->headScript()->appendFile("/js/appointment.js");
		$this->headScript()->appendFile("/js/fancybox/jquery.fancybox-1.3.4.js");
		$this->headScript()->appendFile("/js/main.js");
		echo $this->headScript();
?>
<!--[if gte IE 9]
<style type="text/css">
.gradient {
filter: none;
}
</style>
<![endif]-->
<script type="text/javascript">
	$(document).ready(function() {

		//syntax highlighter
		hljs.tabReplace = '    ';
		hljs.initHighlightingOnLoad();

		//accordion
		$('h3.accordion').accordion({
			defaultOpen: 'body-section1',
			cookieName: 'accordion_nav',
			speed: 'slow',
			animateOpen: function (elem, opts) { //replace the standard slideUp with custom function
				elem.next().slideFadeToggle(opts.speed);
			},
			animateClose: function (elem, opts) { //replace the standard slideDown with custom function
				elem.next().slideFadeToggle(opts.speed);
			}
		});

		$('h3.accordion2').accordion({
			defaultOpen: 'sample-1',
			cookieName: 'accordion2_nav',
			speed: 'slow',
			cssClose: 'accordion2-close', //class you want to assign to a closed accordion header
			cssOpen: 'accordion2-open'
		});

		//custom animation for open/close
		$.fn.slideFadeToggle = function(speed, easing, callback) {
			return this.animate({opacity: 'toggle', height: 'toggle'}, speed, easing, callback);
		};

	});
</script>
<script src="https://apis.google.com/js/platform.js" async defer></script>
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?2w6QTWYC4OicEQ5KkssvmVrj1RPOKm5t";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script-->

<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://ws.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "3976e004-4beb-4aa0-9976-ed6df5240055", doNotHash: true, doNotCopy: false, hashAddressBar: false});</script>
</head>

<body class="bodywhite">
	<?php include_once(APPLICATION_PATH ."/layouts/scripts/page/analyticstracking.php"); ?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3&appId=209727805869982";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<a name="top"></a>
<!--appointments-top -->
<div class="appointments-top">
	<div class="container-fluid" style="padding-left:50px; padding-right:50px;">
		<div class="row">			
			<div class="col-sm-6">
				<a href="/"><img src="/images/doctors-appointments-logo.png" alt="doctors"></a>
			</div>
			<div class="col-sm-6" style="padding-right:0px;">
				<?php echo $this->render('/page/blocks/menu/menu.phtml');?>
			</div>
		</div>
	</div>
</div>
<!--/appointments-top --> 

<?php echo $this->render("/search/full-search.phtml"); ?>

<script language="JavaScript">
	function validateForm(ID) {
		if(ID == 'topmap'){
			document.getElementById('topmap').style.display = '';
			google.maps.event.trigger(map, 'resize');
		}
		else{
			document.getElementById('topmap').style.display = 'none';
			google.maps.event.trigger(map, 'resize');
		}
   }
</script>
 
<!--CONTENT SECTION -->
<div class="allprofile">
	<div class="container-fluid">
    	<div class="row">
    		<?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
<!--/CONTENT SECTION -->
<!-- FOOTER SECTION -->
<?php echo $this->render("/page/footer.phtml"); ?> 