<div id="rightsidemain">
    <div id="rightcontentpart">
        <div id="rightsideheading">
            <img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />
            <span style="margin: 0pt 15px 0pt 0pt; float: right;">
                <a href="/admin/assistant/index/page/<?php echo $this->page?>" class="add">Back</a>
            </span>
			Assistant - Add/Edit
		</div>
        <div id="rightsidecontentpart">
            <span class='red'><?php echo $this->msg; ?></span>
            <form method="post" action="<?php echo $this->form->action?>">
				<table cellspacing="0" cellpadding="0" border="0" class="profile-edit">
					<tbody>
						<tr><td colspan="2"><span class='red'><?php echo $this->msg; ?></span></td></tr>
						<tr>
							<td width="130" id="name-label"><label for="name">Name:</label></td>
							<td class="element"><?php echo $this->form->name;?></td>
						</tr>
						 <tr>
							<td id="phone-label"><label for="phone">Phone:</label></td>
							<td class="element"><?php echo $this->form->telephone;?></td>
						</tr>
						<tr>
							<td id="email-label"><label for="password">Email:</label></td>
							<td class="element"><?php echo $this->form->email;?></td>
						</tr>
						<tr>
							<td id="address-label"><label for="password">Address:</label></td>
							<td class="element"><?php echo $this->form->address;?></td>
						</tr>
						<tr>
							<td id="doctors-label"><label for="password">Doctors:</label></td>
							<td class="element"><?php echo $this->doctorCount;?></td>
						</tr>
						<tr>
							<td id="joindate-label"><label for="password">Member since:</label></td>
							<td class="element"><?php echo $this->joindate;?></td>
						</tr>
						<tr>
							<td></td>
							<td >
								<ul class="errors">
									<?php $errors = $this->form->getErrorMessages();
									if(!empty($errors))foreach($errors as $error)echo "<li>".$error."</li>";
									?>
								</ul>
							</td>
						</tr>
						 <tr>
							<td></td>
							<td class="element"  align="center"><?php echo $this->form->submit;?></td>
						</tr>
						<tr>
							<td colspan="2">Total Doctors
							<?php echo $this->doctorCount; ?>
							</td>
						</tr>
						<tr>
							<th>Number</th>
							<th>Name</th>
						</tr>
						<?php foreach($this->doctorsList as $doctor) { ?>
						<tr>
							<td><?php echo $doctor["id"]; ?></td>
							<td><?php echo $doctor["name"]; ?></td>
						</tr>
						<?php } ?>
					</tbody>
				</table>
			</form>
        </div>
    </div>
    <div class="btm-curve"><img src="/images/admin-images/btm-r-l.gif" align="left" /><img src="/images/admin-images/btm-r-r.gif" align="right" /></div>
</div>