<?php
ob_start();

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php echo $this->lang[429]; ?></title>
</head>
<body>
  <h1><?php echo $this->lang[430]; ?></h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>

  <h3><?php echo $this->lang[431]; ?></h3>
  <p>
      <b><?php echo $this->lang[432]; ?></b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3><?php echo $this->lang[433]; ?></h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3><?php echo $this->lang[434]; ?></h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php endif ?>

</body>
</html>
<?php

$error_content_body=ob_get_clean();
print $error_content_body;
if(isset($_SESSION['error_display']) && $_SESSION['error_display']==true) {
    print $error_content_body;
} else {
	print "<div class='errors-msg'>". $this->lang[435]."</div>";
	//mail('test@siteexample.com', "patient - ERROR MESSAGE",$error_content_body);
}