<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-gb">
<head>
	<link href="/style/style.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="/style/list.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="/style/custom.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="/js/jqtransform/jqtransform.css" media="screen" rel="stylesheet" type="text/css" />
	<script type="text/javascript" src="/js/jquery-1.4.2.js"></script>
	<script type="text/javascript" src="/js/jquery.json-2.2.js"></script>
	<script type="text/javascript" src="/js/jquery.blockUI.js"></script>
	<script type="text/javascript" src="/js/jqtransform/jquery.jqtransform.js"></script>
	
</head>
<body>
<?php //echo $this->headLink()->appendStylesheet('/style/style.css');
$this->headLink()->appendStylesheet('/style/list.css');
?>
<?php
	$todayDate	=	mktime(0,0,0, date("m"), date("d"), date("Y"));

	$requestDate	=	mktime(0,0,0, date("m"), date("d"), date("Y"));
	$jd = GregorianToJD(date("m"), date("d"), date("Y")); //GregorianToJD(m, d, y);
	$reqMM =  date("m");
	$reqDD =  date("d");
	$reqYY =  date("Y");
	
	$requestDay = date("l", $requestDate);

	$weekFirstDate		=	$jd;
	$weekSecondDate		=	$jd+1;
	$weekThirdDate		=	$jd+2;
	$weekFourthDate		=	$jd+3;
	$weekFifthDate		=	$jd+4;
	$weekSixthDate		=	$jd+5;
	$weekSeventhDate	=	$jd+6;

	$preWeekStart	=	$jd-7;
	$nextWeekStart	=	$jd+7;

	$preWeekStartDate = JDToGregorian($preWeekStart);
	$nextWeekStartDate = JDToGregorian($nextWeekStart);

?>
<div class='online-fom show-timeslot' id="popup_main_wrapper">
	<h1 id="appointTitle"><?php echo $this->lang[424]; ?></h1>
	<div id="mapWrap" class="boxWrapper clearfix"> 
		<div class="mapWrap left">
			<div class='maparea'>
				<dir id="map_canvas_fancybox" style="width:215px; height: 160px;"></dir>
			</div>
		</div>
		<div class="addressWrap left">
			<?php $address = $this->profiledata->getStreet().", ".$this->profiledata->getArea().", ".$this->profiledata->getCity()." , ".$this->profiledata->getState()." ".$this->profiledata->getZipcode();
			echo $address; ?>
		</div>
	</div>
	
<?php
/**      APOINTMENTS          **/
?>
		<?php
			$todayDate	=	mktime(0,0,0, date("m"), date("d"), date("Y"));

			if(isset($_REQUEST['start_date']))
			{
				$start_date = $_REQUEST['start_date'];
				$dateArr = explode("/", $start_date);
				$requestDate	=	mktime(0,0,0, $dateArr[0], $dateArr[1], $dateArr[2]);
				$jd = GregorianToJD($dateArr[0], $dateArr[1], $dateArr[2]); //GregorianToJD(m, d, y);
				$reqMM =  $dateArr[0];
				$reqDD =  $dateArr[1];
				$reqYY =  $dateArr[2];
			}else{

				$requestDate	=	mktime(0,0,0, date("m"), date("d"), date("Y"));
				$jd = GregorianToJD(date("m"), date("d"), date("Y")); //GregorianToJD(m, d, y);
				$reqMM =  date("m");
				$reqDD =  date("d");
				$reqYY =  date("Y");
			}

			$requestDay = date("l", $requestDate);

			$weekFirstDate		=	$jd;
			$weekSecondDate		=	$jd+1;
			$weekThirdDate		=	$jd+2;
			$weekFourthDate		=	$jd+3;
			$weekFifthDate		=	$jd+4;
			$weekSixthDate		=	$jd+5;
			$weekSeventhDate	=	$jd+6;

			$preWeekStart	=	$jd-7;
			$nextWeekStart	=	$jd+7;

			/*$day1 = date("l",mktime(0,0,0, $reqMM,$reqDD,$reqYY))." <span>".JDToGregorian($weekFirstDate)."</span>";
			$day2 = date("l",mktime(0,0,0, $reqMM,$reqDD+1,$reqYY))." <span>".JDToGregorian($weekSecondDate)."</span>";
			$day3 = date("l",mktime(0,0,0, $reqMM,$reqDD+2,$reqYY))." <span>".JDToGregorian($weekThirdDate)."</span>";
			$day4 = date("l",mktime(0,0,0, $reqMM,$reqDD+3,$reqYY))." <span>".JDToGregorian($weekFourthDate)."</span>";
			$day5 = date("l",mktime(0,0,0, $reqMM,$reqDD+4,$reqYY))." <span>".JDToGregorian($weekFifthDate)."</span>";
			$day6 = date("l",mktime(0,0,0, $reqMM,$reqDD+5,$reqYY))." <span>".JDToGregorian($weekSixthDate)."</span>";
			$day7 = date("l",mktime(0,0,0, $reqMM,$reqDD+6,$reqYY))." <span>".JDToGregorian($weekSeventhDate)."</span>";
				 */

			$preWeekStartDate = JDToGregorian($preWeekStart);
			$nextWeekStartDate = JDToGregorian($nextWeekStart);
			  ?>
	<div class="boxWrapper clearfix" id="appointWrap">
		<div id="info" class="left">		
			<img width="103" alt="<?php echo $this->profiledata->getFname();?>" title="<?php echo $this->profiledata->getFname();?>" src="<?php echo $this->profileImage;?>" id="profile_pic" >
			<h2><?php echo $this->profiledata->getFname(); ?></h2>
		</div>
		<div class="profile-appoint main_box left" id="dates">
			<a rel="<?php echo $rel_startdate;?>" href="#;" id="div_prev" class="info">
				<span>Previous</span>
			</a>
			<ul id="apointWrapper" class="clearfix">
				<li class="appoint-heading">
					<ul id="appointment-head" class="appoint-list clearfix">
						  <!--li class="appoint-1"><?php //echo $day1; ?></li>
						  <li class="appoint-1"><?php //echo $day2; ?></li>
						  <li class="appoint-1"><?php //echo $day3; ?></li>
						  <li class="appoint-1"><?php //echo $day4; ?></li>
						  <li class="appoint-1"><?php //echo $day5; ?></li>
						  <li class="appoint-1"><?php //echo $day6; ?></li>
					  <li class="appoint-1"><?php //echo $day7; ?></li-->
					</ul>					
				</li>
				<li class="appoint-body">
					<ul class="appint-times">
						<li id="appointment-<?php echo $this->profiledata->getId();?>">
							<ul class="apointments">					
							</ul>
						</li>
					</ul>
				</li>
			</ul>
			<a rel="start_date=<?php echo $nextWeekStartDate;?>" href="#;" id="div_next" class="info">
				<span>Next</span>
			</a> 
		</div>
	</div>
	
		
			

<?php 
$initGeo = trim($this->profiledata->getGeocode());

if($initGeo==''){
    $db = Zend_Registry::get('db');
    $query = "SELECT latitude, longitude FROM zipcodesusa WHERE zipcode = '{$this->profiledata->getZipcode()}'";
    $select = $db->query($query);
    $result = $select->fetch();
    if ($result) {
        $initGeo = "{$result->latitude},{$result->longitude}";
    }
}

$config = new Zend_Config_Ini(APPLICATION_PATH.'/configs/'.APPLICATION_INI, APPLICATION_ENV);

$server_name = $_SERVER['HTTP_HOST'];
if($server_name == "50.16.194.135")
    $map_key = "ABQIAAAALCGRfkfi99ibqG2IfwnMWBQmHla76v5ksp53EMVzKw7N5weHFhSBZP1ogQuqwKbSd5XY_P7IiFTROg";
else
    $map_key = $config->patient->googleMapKey;
?>


<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=<?php echo $map_key;?>"
            type="text/javascript"></script>
<script type="text/javascript">

 function initialize_fancybox() {
      if (GBrowserIsCompatible()) {
        var map = new GMap2(document.getElementById("map_canvas_fancybox"));

        var str = '<?php echo $initGeo;?>';
        var brk = str.split(',');
        var latitude = parseFloat(brk[0]);
        var longitude = parseFloat(brk[1]);
        map.setCenter(new GLatLng(latitude,longitude), 14);

      
        map.setUIToDefault();

       // Create a base icon for all of our markers that specifies the
        // shadow, icon dimensions, etc.
        var baseIcon = new GIcon(G_DEFAULT_ICON);
        baseIcon.shadow = "http://www.google.com/mapfiles/shadow50.png";
        baseIcon.iconSize = new GSize(26, 34);
        baseIcon.shadowSize = new GSize(37, 34);
        baseIcon.iconAnchor = new GPoint(9, 34);
        baseIcon.infoWindowAnchor = new GPoint(9, 2);



        // Creates a marker whose info window displays the letter corresponding
        // to the given index.
        function createMarker(point, infoHtml) {
          // Create a lettered icon for this point using our icon class
          var mapIcon = new GIcon(baseIcon);
          mapIcon.image = "/images/markers/marker0.png";

          // Set up our GMarkerOptions object
          markerOptions = { icon:mapIcon };
          var marker = new GMarker(point, markerOptions);

          return marker;
        }

        var latlng = new GLatLng(latitude,longitude);
        map.addOverlay(createMarker(latlng, ''));
      }
    }

   initialize_fancybox();
   window.unload = GUnload;
    </script>
	<!-----------------------------------------------Timeslot js ----------------------------------------------->
<script type="text/javascript">

     jQuery(".info").click(
        function () {
            //alert(1);
            start_date = jQuery(this).attr('rel');
                if(start_date!="") {

                    start_date_arr = start_date.split('=');

                    if(jQuery.trim(start_date_arr[1])!=''){
                       //$('#appointment-head-fancybox').block({ message: null });
                        jQuery.blockUI({ overlayCSS: { backgroundColor: '#000' } });
                        loadSlotData(start_date_arr[1], 'c');
                        setTimeout(jQuery.unblockUI, 2000);
                    }

                }
            }
        );

    function loadSlotData(start_date, load_type)
    {
        // load_type variable use to check if function called on page load or on click.
        if(start_date!="") {

                drid_val = <?php echo $this->profiledata->getId();?>;
                //jQuery("#drid_current").val(drid_val);
                jQuery.post('/profile/timeslot/', {drid: drid_val, start_date:start_date,disp:'fancy' },

                function(data){
                    //alert(data);return false;
                    var decoded = $.json.decode(data);
                    dr_div_id = "#appointment-"+decoded['drid'];//2
                    jQuery(dr_div_id).html(decoded['return_data']);//1
                    //alert(ret_data_arr[1]);
                    jQuery("#appointment-head").html(decoded['appointment_head']); //3
                    if(load_type=='c'){ // if time slot loading from on click event.
                        //if(decoded['button_prev_date']!="")
                            jQuery("#div_prev").attr('rel','start_date='+decoded['button_prev_date']);//4
                        jQuery("#div_next").attr('rel','start_date='+decoded['button_next_date']); //5
                    }

                    initiate_click();
bindClickTimeslot();
                }, false);

        }
       
    }



 function bindClickTimeslot(){
        $('a.slots').bind({
              click: function() {
                  window.parent.location=$(this).attr('href');
                return false;
              }
            });
        }

    jQuery(document).ready(function() {
        loadSlotData("<?php echo date('m/d/Y')?>", 'p');

    } );

   function initiate_click(){
       jQuery('.moreLink').click(function(){
            jQuery(this).hide();
            jQuery('#'+jQuery(this).attr('rel')).fadeIn(500);
        });
   }


jQuery(document).ready(function(){

     jQuery('#reason_to_visit').change(function(){
        $.post('/profile/set-reasonforvisit/', {
                reason:$(this).val()
            },
            function(html){
            });
     });
	 $('div.jqtransform').jqTransform();

});

</script>
					<?php// echo $this->render('search/randezvous.phtml'); ?>					
<?php /*** end APOINTMENTS ***/ ?>
	
</div>
</body>
</html>
			