<!-- FOOTER SECTION -->
<footer>
  <div class="footer-top">
    <div class="footertop-inner clearfix">
      <div class="footerboxes box01">
        <h3>About doctors</h3>
        <p>doctors is a service that helps patients and doctors communicate in a very rich experience through the doctors online platform.
            Patients can book appointments online, send secure messages to their doctor, write reviews about doctors and much more!</p>
        <p><a href="/about">Learn more</a></p>
      </div>
      <div class="footerboxes box02">
        <h3>Latest on Twitter</h3>
        <div id="footerTwitter"></div>
        <a href="http://twitter.com/doctors" target="_blank">follow us on Twitter</a>
      </div>
      <div class="footerboxes box03">
        <h3>Our Features</h3>
        <div class="services">
          <ul>
            <li><a href="/about"><img src="/images/service-a.png" alt=""></a></li>
            <li><a href="/about"><img src="/images/service-b.png" alt=""></a></li>
            <li><a href="/about"><img src="/images/service-c.png" alt=""></a></li>
            <li><a href="/about"><img src="/images/service-d.png" alt=""></a></li>
            <li><a href="/about"><img src="/images/service-e.png" alt=""></a></li>
            <li><a href="/about"><img src="/images/service-f.png" alt=""></a></li>
            <li><a href="/about"><img src="/images/service-g.png" alt=""></a></li>
            <li><a href="/about"><img src="/images/service-i.png" alt=""></a></li>
          </ul>
        </div>
      </div>
      <div class="footerboxes box04">
        <div class="newsletterbox">
          <h3>Newsletter</h3>
          <div class="nwsletterform clearfix">
          	<!-- Begin MailChimp Signup Form -->
			<div id="mc_embed_signup">
				<form action="//a1healthtech.us10.list-manage.com/subscribe/post?u=42897eccfb82c7136cf74c2e8&amp;id=9b3380f319" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
				    <div id="mc_embed_signup_scroll">
						<div class="mc-field-group">
							<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="Subscribe to our newsletter">
							<input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
						</div>
						<div id="mce-responses" class="clear">
							<div class="response" id="mce-error-response" style="display:none"></div>
							<div class="response" id="mce-success-response" style="display:none"></div>
						</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
					    <div style="position: absolute; left: -5000px;"><input type="text" name="b_42897eccfb82c7136cf74c2e8_9b3380f319" tabindex="-1" value=""></div>
				    </div>
				</form>
			</div>

			<!--End mc_embed_signup-->
          </div>
        </div>
        <div class="bottom-socialmedia">
          <h3>Follow us</h3>
          <ul>
            <li><a href="https://www.facebook.com/Likedoctors" class="social1 fadeThis"><span class="hover">Facebook</span></a></li>
            <li><a href="https://twitter.com/doctors" class="social2 fadeThis"><span class="hover">Twitter</span></a></li>
            <!-- <li><a href="#" class="social3 fadeThis"><span class="hover">LinkedIn</span></a></li>
            <li><a href="#" class="social4 fadeThis"><span class="hover">Google Plus</span></a></li> -->
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="footerbottom-inner clearfix">
      <p class="copyright">Copyright A1 Healthcare Technologies LLC &copy; <?php echo date("Y"); ?>. All rights reserved.</p>
      <nav>
        <ul>
         <!--<li><a href="/features">Features</a></li>-->
          <li><a href="/about"><?php echo $this->lang[133]; ?></a></li>
          <li><a href="/register">JOIN NOW</a></li>
          <li><a href="/terms-of-use-and-disclaimers">Terms &amp; Conditions</a></li>
          <li><a href="/contact-us"><?php echo $this->lang[27]; ?></a></li>
          <!--<li><a href="#">BLOG</a></li>-->
        </ul>
      </nav>
    </div>
  </div>
  <?php $config = new Zend_Config_Ini(APPLICATION_PATH.'/configs/'.APPLICATION_INI, APPLICATION_ENV); ?>	
</footer>
<!-- /FOOTER SECTION -->

<script src="/js/responsive-nav.js" type="text/javascript"></script>
<script src="/js/jquery.meanmenu.min.js" type="text/javascript"></script>
<script>
	/* Mean Menu for Mobile */
	$('nav#main-menu').meanmenu({
		meanMenuContainer :  $('#menu-container'),
		meanRevealPosition:  'right',
		meanScreenWidth   :  767
	});
</script>
<script>
	jQuery(x).parent('.mean-bar').next('.mean-push').remove();		
	jQuery(x).parent('.mean-bar').remove();

	jQuery('nav#main-menu').meanmenu({
		meanMenuContainer :  jQuery('#menu-container'),
		meanRevealPosition:  'right',
		meanScreenWidth   :  767	
	});
</script>


<script src="/js/core.minf1b2.js"></script> 
<script src="/js/bootstrap.min.js"></script>
<script src="/js/docs.min.js"></script>
  
<script src="/js/device.min.js"></script>
<script src="/js/cherry.lazy-load.js"></script>
   
    
</body>
</html>
