<a name="top"></a>
<div class="full-white gbr">
<!--TOP SECTION -->
	<div class="container bottom-border">
    	<div class="row">
        	<div class="col-sm-6">
            	<div class="topcatchline">Welcome to <span>doctors!</span> Manage your health online and book appointments instantly!</div>
            </div>
            <div class="col-sm-6">
            	<?php echo $this->render('/page/blocks/menu/menu.phtml');?>
            </div>
        </div>
    </div>
<!--/TOP SECTION -->
<!--NAV SECTION -->
	<div class="container">
    	<div class="row">
        	<div class="col-sm-6">
            	<div class="logo "><a href="/"><img src="/images/doctors-logo.png" alt="doctors"></a></div>
            </div>
            <div class="col-sm-6 mainnav ">
            <nav class="nav-main pull-right">
                <div id="menu-container">
            	<nav id="main-menu" class="pull-right">
                	<ul class="group">
                		<li>
			          		<a href="/">Home</a>
			          	</li>
			          	<!--<li>
			          		<a href="/features" <?php if($this->controllerName=='index' && $this->actionName=="features" ) { ?> class="selected" <?php } ?>>Features</a>
			          	</li>-->
			          	<li>
			          		<a href="/about" <?php if($this->controllerName=='index' && $this->actionName=="about-us" ) { ?> class="selected" <?php } ?>>About Us</a>
			          	</li>
			          	<li>
			          		<a href="/contact-us" <?php if($this->controllerName=='index' && $this->actionName=="contact-us" ) { ?> class="selected" <?php } ?>>Contact Us</a>
			          	</li>
					</ul>
                </nav>
                </div>
                </nav>
            </div>
        </div>
    </div>
<!--/NAV SECTION -->
</div>

